# Generated by Django 3.0.2 on 2021-03-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=10)),
                ('tole', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('house_no', models.CharField(max_length=30)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Citizen')),
            ],
        ),
    ]
