# Generated by Django 3.0.2 on 2021-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(default=0, verbose_name=((0, 'Permanent'), (1, 'Temporary'))),
        ),
    ]
