# Generated by Django 3.0.2 on 2021-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(choices=[(0, 'Permanent'), (1, 'Temporary')], default=0),
        ),
    ]
