# Generated by Django 3.0.2 on 2021-03-19 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=16)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('father_name', models.CharField(max_length=50)),
                ('grandfather_name', models.CharField(max_length=50)),
                ('father_citizen_number', models.CharField(blank=True, max_length=12)),
                ('birth_certificate_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('applicant_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('father_citizenship_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
