# Generated by Django 3.0.2 on 2021-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='husband_citizen_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='citizen',
            name='husband_citizenship_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='husband_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citizen',
            name='mother_citizen_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='citizen',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
