# Generated by Django 3.0.2 on 2021-03-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210319_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='mother_citizenship_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
