# Generated by Django 3.0.2 on 2021-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_citizen_mother_citizenship_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
